/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GateRouteImport } from './routes/gate'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as DevPosterractV2RouteImport } from './routes/dev/posterract-v2'
import { Route as DevHyperkitRouteImport } from './routes/dev/hyperkit'
import { Route as DevCoreRouteImport } from './routes/dev/core'
import { Route as AppVaultRouteImport } from './routes/_app/vault'
import { Route as AppUplinkRouteImport } from './routes/_app/uplink'
import { Route as AppTransmissionsRouteImport } from './routes/_app/transmissions'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPortalsRouteImport } from './routes/_app/portals'
import { Route as AppForgeRouteImport } from './routes/_app/forge'
import { Route as AppEchoesRouteImport } from './routes/_app/echoes'
import { Route as AppContinuumRouteImport } from './routes/_app/continuum'
import { Route as AppComposeRouteImport } from './routes/_app/compose'
import { Route as OauthCallbackProviderRouteImport } from './routes/oauth.callback.$provider'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DevPosterractV2Route = DevPosterractV2RouteImport.update({
  id: '/dev/posterract-v2',
  path: '/dev/posterract-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHyperkitRoute = DevHyperkitRouteImport.update({
  id: '/dev/hyperkit',
  path: '/dev/hyperkit',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCoreRoute = DevCoreRouteImport.update({
  id: '/dev/core',
  path: '/dev/core',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppUplinkRoute = AppUplinkRouteImport.update({
  id: '/uplink',
  path: '/uplink',
  getParentRoute: () => AppRoute,
} as any)
const AppTransmissionsRoute = AppTransmissionsRouteImport.update({
  id: '/transmissions',
  path: '/transmissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalsRoute = AppPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AppRoute,
} as any)
const AppForgeRoute = AppForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => AppRoute,
} as any)
const AppEchoesRoute = AppEchoesRouteImport.update({
  id: '/echoes',
  path: '/echoes',
  getParentRoute: () => AppRoute,
} as any)
const AppContinuumRoute = AppContinuumRouteImport.update({
  id: '/continuum',
  path: '/continuum',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const OauthCallbackProviderRoute = OauthCallbackProviderRouteImport.update({
  id: '/oauth/callback/$provider',
  path: '/oauth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/enter': typeof EnterRoute
  '/gate': typeof GateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compose': typeof AppComposeRoute
  '/continuum': typeof AppContinuumRoute
  '/echoes': typeof AppEchoesRoute
  '/forge': typeof AppForgeRoute
  '/portals': typeof AppPortalsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/transmissions': typeof AppTransmissionsRoute
  '/uplink': typeof AppUplinkRoute
  '/vault': typeof AppVaultRoute
  '/dev/core': typeof DevCoreRoute
  '/dev/hyperkit': typeof DevHyperkitRoute
  '/dev/posterract-v2': typeof DevPosterractV2Route
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/data-deletion': typeof DataDeletionRoute
  '/enter': typeof EnterRoute
  '/gate': typeof GateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compose': typeof AppComposeRoute
  '/continuum': typeof AppContinuumRoute
  '/echoes': typeof AppEchoesRoute
  '/forge': typeof AppForgeRoute
  '/portals': typeof AppPortalsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/transmissions': typeof AppTransmissionsRoute
  '/uplink': typeof AppUplinkRoute
  '/vault': typeof AppVaultRoute
  '/dev/core': typeof DevCoreRoute
  '/dev/hyperkit': typeof DevHyperkitRoute
  '/dev/posterract-v2': typeof DevPosterractV2Route
  '/': typeof AppIndexRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/enter': typeof EnterRoute
  '/gate': typeof GateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/compose': typeof AppComposeRoute
  '/_app/continuum': typeof AppContinuumRoute
  '/_app/echoes': typeof AppEchoesRoute
  '/_app/forge': typeof AppForgeRoute
  '/_app/portals': typeof AppPortalsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/transmissions': typeof AppTransmissionsRoute
  '/_app/uplink': typeof AppUplinkRoute
  '/_app/vault': typeof AppVaultRoute
  '/dev/core': typeof DevCoreRoute
  '/dev/hyperkit': typeof DevHyperkitRoute
  '/dev/posterract-v2': typeof DevPosterractV2Route
  '/_app/': typeof AppIndexRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/enter'
    | '/gate'
    | '/privacy'
    | '/terms'
    | '/compose'
    | '/continuum'
    | '/echoes'
    | '/forge'
    | '/portals'
    | '/settings'
    | '/skills'
    | '/transmissions'
    | '/uplink'
    | '/vault'
    | '/dev/core'
    | '/dev/hyperkit'
    | '/dev/posterract-v2'
    | '/oauth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/data-deletion'
    | '/enter'
    | '/gate'
    | '/privacy'
    | '/terms'
    | '/compose'
    | '/continuum'
    | '/echoes'
    | '/forge'
    | '/portals'
    | '/settings'
    | '/skills'
    | '/transmissions'
    | '/uplink'
    | '/vault'
    | '/dev/core'
    | '/dev/hyperkit'
    | '/dev/posterract-v2'
    | '/'
    | '/oauth/callback/$provider'
  id:
    | '__root__'
    | '/_app'
    | '/data-deletion'
    | '/enter'
    | '/gate'
    | '/privacy'
    | '/terms'
    | '/_app/compose'
    | '/_app/continuum'
    | '/_app/echoes'
    | '/_app/forge'
    | '/_app/portals'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/transmissions'
    | '/_app/uplink'
    | '/_app/vault'
    | '/dev/core'
    | '/dev/hyperkit'
    | '/dev/posterract-v2'
    | '/_app/'
    | '/oauth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  EnterRoute: typeof EnterRoute
  GateRoute: typeof GateRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  DevCoreRoute: typeof DevCoreRoute
  DevHyperkitRoute: typeof DevHyperkitRoute
  DevPosterractV2Route: typeof DevPosterractV2Route
  OauthCallbackProviderRoute: typeof OauthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/posterract-v2': {
      id: '/dev/posterract-v2'
      path: '/dev/posterract-v2'
      fullPath: '/dev/posterract-v2'
      preLoaderRoute: typeof DevPosterractV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/hyperkit': {
      id: '/dev/hyperkit'
      path: '/dev/hyperkit'
      fullPath: '/dev/hyperkit'
      preLoaderRoute: typeof DevHyperkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/core': {
      id: '/dev/core'
      path: '/dev/core'
      fullPath: '/dev/core'
      preLoaderRoute: typeof DevCoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uplink': {
      id: '/_app/uplink'
      path: '/uplink'
      fullPath: '/uplink'
      preLoaderRoute: typeof AppUplinkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transmissions': {
      id: '/_app/transmissions'
      path: '/transmissions'
      fullPath: '/transmissions'
      preLoaderRoute: typeof AppTransmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portals': {
      id: '/_app/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof AppPortalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forge': {
      id: '/_app/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof AppForgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/echoes': {
      id: '/_app/echoes'
      path: '/echoes'
      fullPath: '/echoes'
      preLoaderRoute: typeof AppEchoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/continuum': {
      id: '/_app/continuum'
      path: '/continuum'
      fullPath: '/continuum'
      preLoaderRoute: typeof AppContinuumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compose': {
      id: '/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/callback/$provider': {
      id: '/oauth/callback/$provider'
      path: '/oauth/callback/$provider'
      fullPath: '/oauth/callback/$provider'
      preLoaderRoute: typeof OauthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppComposeRoute: typeof AppComposeRoute
  AppContinuumRoute: typeof AppContinuumRoute
  AppEchoesRoute: typeof AppEchoesRoute
  AppForgeRoute: typeof AppForgeRoute
  AppPortalsRoute: typeof AppPortalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTransmissionsRoute: typeof AppTransmissionsRoute
  AppUplinkRoute: typeof AppUplinkRoute
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComposeRoute: AppComposeRoute,
  AppContinuumRoute: AppContinuumRoute,
  AppEchoesRoute: AppEchoesRoute,
  AppForgeRoute: AppForgeRoute,
  AppPortalsRoute: AppPortalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTransmissionsRoute: AppTransmissionsRoute,
  AppUplinkRoute: AppUplinkRoute,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  EnterRoute: EnterRoute,
  GateRoute: GateRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  DevCoreRoute: DevCoreRoute,
  DevHyperkitRoute: DevHyperkitRoute,
  DevPosterractV2Route: DevPosterractV2Route,
  OauthCallbackProviderRoute: OauthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
