/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import { AMOUNT, DIRECTION_OPTIONS, SHAPE_OPTIONS, SPOT } from './shared';

import type { FamilyDef } from '../types';

export const ARRANGE: FamilyDef = {
  id: 'arrange',
  label: 'Arrange',
  exclusive: false,
  ask:
    'Does the command ask to change where an element is or how big it is, how it is turned, its layer order (in front, behind), '
    + 'or to line up, space out, group, duplicate, copy, paste, delete, rename, hide or show, or lock elements, turn a shape into another, '
    + 'or swap the file a clip plays? For example "move it left", "make it bigger", "put the logo top right", "align these left", '
    + '"delete the badge", "duplicate it", "hide the title", "send it to the back". Not its color or look, not its timing, not an animation.',
  slots: {
    spot: SPOT,
    direction: { kind: 'choice', ask: 'Which way does the command ask for it to move?', options: DIRECTION_OPTIONS },
    amount: AMOUNT,
    by: { kind: 'number', text: 'How far to move it, in pixels or as a percentage of the frame.', units: ['px', '%'] },
    x: { kind: 'number', text: 'Its horizontal position, x, in pixels.', units: ['px', '%'] },
    y: { kind: 'number', text: 'Its vertical position, y, in pixels.', units: ['px', '%'] },
    anchor: {
      kind: 'element',
      ask: 'Which other element does the command put it next to, size it like, or put it in front of or behind?',
    },
    relation: {
      kind: 'choice',
      ask: 'Where does the command put it against the other element?',
      options: {
        below: 'Below it, under it, beneath it.',
        above: 'Above it, over it, on top of it on screen.',
        left: 'To its left.',
        right: 'To its right.',
        center: 'Centered on it, in its middle.',
        same: 'In the same place as it, on top of it exactly.',
      },
    },
    gap: { kind: 'number', text: 'The gap to leave between them, in pixels.', units: ['px'] },
    align_how: {
      kind: 'choice',
      ask: 'How does the command ask for them to line up?',
      options: {
        left: 'Their left edges lined up: aligned left.',
        'center-horizontal': 'Their centers lined up on one vertical line: centered horizontally, left to right.',
        right: 'Their right edges lined up: aligned right.',
        top: 'Their top edges lined up: aligned to the top.',
        'center-vertical': 'Their middles lined up on one horizontal line: centered vertically, top to bottom.',
        bottom: 'Their bottom edges lined up: aligned to the bottom.',
      },
    },
    axis: {
      kind: 'choice',
      ask: 'Which way does the command ask for them to be spaced out?',
      options: { x: 'Across, side by side, horizontally.', y: 'Down, one above the other, vertically.' },
    },
    size_dir: {
      kind: 'choice',
      ask: 'Does the command ask for it to be bigger or smaller?',
      options: { bigger: 'Bigger, larger, enlarged, scaled up.', smaller: 'Smaller, reduced, shrunk, scaled down.' },
    },
    scale: { kind: 'number', text: 'Its overall size as a multiple or a percentage: twice as big, half the size, 150 percent.', units: ['x', '%'] },
    width: { kind: 'number', text: 'Its width, in pixels or as a percentage of the frame.', units: ['px', '%'] },
    height: { kind: 'number', text: 'Its height, in pixels or as a percentage of the frame.', units: ['px', '%'] },
    fill_how: {
      kind: 'choice',
      ask: 'How does the command ask for it to be sized to the frame or to the other element?',
      options: {
        fill: 'Fill the whole frame, full screen, edge to edge.',
        fit: 'Fit inside the frame, as big as it can be without being cut off.',
        'full-width': 'As wide as the frame.',
        'full-height': 'As tall as the frame.',
        'half-width': 'Half the width of the frame.',
        'half-height': 'Half the height of the frame.',
        same: 'The same size as the other element.',
      },
    },
    degrees: { kind: 'number', text: 'How far to turn it, in degrees.', units: ['deg'] },
    rotate_how: {
      kind: 'choice',
      ask: 'How does the command ask for it to be turned?',
      options: {
        by: 'By an amount: a number of degrees, a little, a lot.',
        'upside-down': 'Upside down: half a turn.',
        'quarter-right': 'A quarter turn to the right, clockwise.',
        'quarter-left': 'A quarter turn to the left, counterclockwise.',
        straight: 'Straight again: no rotation, level.',
      },
    },
    spin: {
      kind: 'choice',
      ask: 'Which way does the command ask for it to turn?',
      options: { clockwise: 'Clockwise, to the right.', counterclockwise: 'Counterclockwise, anticlockwise, to the left.' },
    },
    layer_how: {
      kind: 'choice',
      ask: 'Where in the layer order does the command put it?',
      options: {
        front: 'In front of everything, on top, to the front.',
        back: 'Behind everything, underneath, to the back.',
        forward: 'One layer forward, up a layer.',
        backward: 'One layer back, down a layer.',
        'in-front-of': 'Just in front of the other element.',
        behind: 'Just behind the other element.',
      },
    },
    container: {
      kind: 'element',
      ask: 'Which group, sequence or scene does the command put it into?',
      containers: true,
    },
    count: { kind: 'number', text: 'How many copies.', units: ['count', 'x'] },
    words: { kind: 'words', text: 'a new name' },
    shape_kind: { kind: 'choice', ask: 'Which kind of shape does the command ask for it to become?', options: SHAPE_OPTIONS },
    hide: { kind: 'onoff', ask: 'Does the command ask to hide it (yes), rather than to show it again (no)?', yes: 'Hide', no: 'Show' },
    lock: { kind: 'onoff', ask: 'Does the command ask to lock it (yes), rather than to unlock it (no)?', yes: 'Lock', no: 'Unlock' },
    keep_ratio: {
      kind: 'onoff',
      ask: 'Does the command ask to keep its proportions when it is resized (yes), rather than to let them change (no)?',
      yes: 'Keep proportions',
      no: 'Free proportions',
    },
    inset: { kind: 'number', text: 'How far from the edge of the frame, in pixels.', units: ['px'] },
    asset: { kind: 'asset', ask: 'Which file from the library should it play instead?', types: ['video', 'image', 'audio', 'sequence'] },
  },
  intents: [
    {
      id: 'arrange.place',
      needs: ['spot'],
      label: 'Place',
      text: {
        what: 'Put an element at a named spot in the frame: a corner, an edge, the center, the upper or lower third.',
        notFor: 'Not moving it by an amount, not the side an animation comes in from, not lining several up with each other.',
        examples: ['put the logo in the top right', 'move the title to the lower third', 'center the text in the frame', 'send the badge to the bottom left corner'],
      },
      uses: ['spot'],
      target: 'many',
      covers: ['place'],
    },
    {
      id: 'arrange.move',
      needs: ['direction'],
      label: 'Move',
      text: {
        what: 'Move an element on screen by an amount: left, right, up or down.',
        notFor: 'Not a named spot such as a corner, and not earlier or later in time.',
        examples: ['move it left a bit', 'nudge the title up', 'shift the logo 50 pixels right', 'move it down a lot'],
      },
      uses: ['direction', 'amount', 'by'],
      target: 'many',
      covers: ['x', 'y', 'nudgeSelection', 'canvas.nudge-left', 'canvas.nudge-right', 'canvas.nudge-up', 'canvas.nudge-down', 'canvas.nudge-left-far', 'canvas.nudge-right-far', 'canvas.nudge-up-far', 'canvas.nudge-down-far'],
    },
    {
      id: 'arrange.position',
      needs: ['x', 'y'],
      label: 'Position',
      text: {
        what: "Set an element's exact position in pixels: x, y, or both.",
        examples: ['set x to 100', 'put it at 200 by 400', 'y 80'],
      },
      uses: ['x', 'y'],
      target: 'many',
      covers: ['x', 'y'],
    },
    {
      id: 'arrange.next-to',
      needs: ['anchor'],
      label: 'Next to',
      text: {
        what: 'Put an element next to another element: above, below, to its left or right, centered on it, or in the same place.',
        notFor: 'Not in front of or behind it in the layer order.',
        examples: ['put the logo under the title', 'move the badge above the headline', 'center the text on the circle', 'place the button to the right of the logo'],
      },
      uses: ['anchor', 'relation', 'gap'],
      target: 'many',
      covers: ['x', 'y'],
    },
    {
      id: 'arrange.align',
      needs: ['align_how'],
      label: 'Align',
      text: {
        what: 'Line elements up with each other — their left edges, right edges, tops, bottoms or centers — or one element against the frame.',
        notFor: 'Not how the lines inside a text line up, and not a named spot in the frame.',
        examples: ['align these left', 'line them up along the top', 'center them horizontally', 'align the bottoms of the logo and the badge'],
      },
      uses: ['align_how'],
      target: 'many',
      covers: ['alignSelection'],
    },
    {
      id: 'arrange.distribute',
      label: 'Space out',
      text: {
        what: 'Space three or more elements out evenly, across or down.',
        examples: ['space these out evenly', 'distribute them vertically', 'even out the gaps between the icons'],
      },
      uses: ['axis'],
      target: 'many',
      covers: ['distributeSelection'],
    },
    {
      id: 'arrange.size',
      needs: ['size_dir', 'scale', 'width', 'height'],
      label: 'Resize',
      text: {
        what: 'Make an element bigger or smaller, or set its size, scale, width or height.',
        notFor: 'Not louder or quieter, not longer or shorter in time.',
        examples: ['make it bigger', 'shrink the logo a little', 'twice as big', 'set the width to 400', 'scale it to 50 percent'],
      },
      uses: ['size_dir', 'amount', 'scale', 'width', 'height'],
      target: 'many',
      covers: ['scale', 'width', 'height', 'fontSize'],
    },
    {
      id: 'arrange.fill-frame',
      needs: ['fill_how'],
      label: 'Size to the frame',
      text: {
        what: 'Size an element to the frame or to another element: fill the whole frame, fit inside it, full width, full height, half of it, or the same size as another element.',
        examples: ['fill the screen with the video', 'make it full width', 'same size as the title', 'half the width of the screen'],
      },
      uses: ['fill_how', 'anchor'],
      target: 'many',
      covers: ['width', 'height', 'x', 'y'],
    },
    {
      id: 'arrange.rotate',
      needs: ['degrees', 'rotate_how', 'spin'],
      label: 'Rotate',
      text: {
        what: 'Turn an element: by degrees, a quarter turn, upside down, or straight again.',
        notFor: 'Not a spinning animation.',
        examples: ['rotate it 45 degrees', 'turn the logo upside down', 'straighten it', 'tilt it a little to the right'],
      },
      uses: ['degrees', 'rotate_how', 'spin', 'amount'],
      target: 'many',
      covers: ['rotation'],
    },
    {
      id: 'arrange.layer',
      needs: ['layer_how'],
      label: 'Layer order',
      text: {
        what: 'Change the layer order: bring to the front, send to the back, one layer forward or back, or just in front of or behind another element.',
        notFor: 'Not a place in the frame such as the top or the bottom.',
        examples: ['bring the title to the front', 'send it behind the logo', 'one layer up', 'put the video at the back'],
      },
      uses: ['layer_how', 'anchor'],
      target: 'many',
      covers: ['reparent', 'restackSelection', 'edit.bring-front', 'edit.send-back'],
    },
    {
      id: 'arrange.into',
      needs: ['container'],
      label: 'Move into',
      text: {
        what: 'Move an element into a group, a sequence or another scene.',
        examples: ['move this into the second scene', 'put it in the group', 'add the clip to the sequence'],
      },
      uses: ['container'],
      target: 'many',
      covers: ['canvasMove'],
    },
    {
      id: 'arrange.duplicate',
      label: 'Duplicate',
      text: {
        what: 'Make one or more copies of an element in the video, in the same place.',
        notFor: 'Not copying to the clipboard to paste later.',
        examples: ['duplicate it', 'make three copies of the circle', 'duplicate the title twice'],
      },
      uses: ['count'],
      target: 'many',
      command: 'edit.duplicate',
      covers: ['duplicate'],
    },
    {
      id: 'arrange.delete',
      label: 'Delete',
      text: {
        what: 'Delete elements from the video.',
        notFor: 'Not deleting a marker, a filter or an animation; not hiding.',
        examples: ['delete the badge', 'remove the logo', 'get rid of this', 'throw away the second clip'],
      },
      target: 'many',
      risk: 'confirm',
      command: 'edit.delete',
      covers: ['remove'],
    },
    {
      id: 'arrange.ripple-delete',
      label: 'Ripple delete',
      text: {
        what: 'Delete clips and close the gap they leave, pulling everything after them earlier.',
        examples: ['delete it and close the gap', 'ripple delete this clip', 'remove the clip and pull the rest up'],
      },
      target: 'many',
      risk: 'confirm',
      command: 'edit.ripple-delete',
      covers: ['rippleDeleteSelection'],
    },
    {
      id: 'arrange.group',
      label: 'Group',
      text: { what: 'Put elements together in a group, so they move as one.', examples: ['group these', 'group the title and the logo'] },
      target: 'many',
      command: 'edit.group',
      covers: ['group'],
    },
    {
      id: 'arrange.ungroup',
      label: 'Ungroup',
      text: {
        what: 'Break a group apart, so the elements in it stand on their own again.',
        notFor: 'Not cutting a clip in two.',
        examples: ['ungroup it', 'break the group apart', 'they do not need to move as one any more'],
      },
      target: 'many',
      command: 'edit.ungroup',
    },
    {
      id: 'arrange.wrap-sequence',
      label: 'Wrap in a sequence',
      text: { what: 'Put clips in a sequence, so they play one after another.', examples: ['put these in a sequence', 'make these play one after another'] },
      target: 'many',
      command: 'edit.wrap-sequence',
      covers: ['sequence'],
    },
    {
      id: 'arrange.unwrap-sequence',
      label: 'Unwrap the sequence',
      text: {
        what: 'Break a sequence apart, so its clips stand on their own again rather than playing one after another.',
        notFor: 'Not cutting a clip in two.',
        examples: ['unwrap the sequence', 'take the clips out of the sequence', 'they should not run one after another any more'],
      },
      target: 'many',
      command: 'edit.unwrap-sequence',
    },
    {
      id: 'arrange.wrap-scene',
      label: 'Wrap in a scene',
      text: { what: 'Turn elements into a scene of their own.', examples: ['make a scene from these', 'wrap this in its own scene'] },
      target: 'many',
      command: 'edit.wrap-scene',
    },
    {
      id: 'arrange.copy',
      label: 'Copy',
      text: { what: 'Copy elements to the clipboard, to paste later.', notFor: 'Not making a copy in the video now (duplicating).', examples: ['copy this', 'copy the logo to the clipboard'] },
      target: 'many',
      command: 'edit.copy',
    },
    {
      id: 'arrange.cut',
      label: 'Cut to the clipboard',
      text: { what: 'Cut elements to the clipboard, removing them, to paste somewhere else.', notFor: 'Not splitting a clip in two.', examples: ['cut this to the clipboard', 'cut the badge so I can paste it'] },
      target: 'many',
      command: 'edit.cut',
    },
    {
      id: 'arrange.paste',
      label: 'Paste',
      text: { what: 'Paste what was copied or cut.', examples: ['paste', 'paste it here'] },
      target: 'none',
      command: 'edit.paste',
    },
    {
      id: 'arrange.rename',
      needs: ['words'],
      label: 'Rename',
      text: {
        what: 'Rename an element in the layers list.',
        notFor: 'Not changing the words a text says.',
        examples: ['rename the badge to Live', 'call this layer background', 'name it intro title'],
      },
      uses: ['words'],
      target: 'one',
      covers: ['name'],
    },
    {
      id: 'arrange.change-shape',
      needs: ['shape_kind'],
      label: 'Change the shape',
      text: {
        what: 'Turn a shape into another kind of shape.',
        examples: ['make it a star', 'turn the square into a circle', 'change the rectangle to a triangle'],
      },
      uses: ['shape_kind'],
      target: 'many',
      tags: ['rect', 'ellipse', 'polygon'],
      covers: ['changeShape', 'points'],
    },
    {
      id: 'arrange.visibility',
      needs: ['hide'],
      label: 'Hide or show',
      text: {
        what: 'Hide an element, or show it again.',
        notFor: 'Not fading it in or out, not making it see-through.',
        examples: ['hide the logo', 'show the badge again', 'make it invisible', 'unhide the title'],
      },
      uses: ['hide'],
      target: 'many',
      covers: ['hidden', 'edit.hide'],
    },
    {
      id: 'arrange.lock',
      needs: ['lock'],
      label: 'Lock',
      text: { what: 'Lock an element so it cannot be moved or changed, or unlock it.', examples: ['lock this layer', 'unlock the video', 'lock the background'] },
      uses: ['lock'],
      target: 'many',
      covers: ['locked'],
    },
    {
      id: 'arrange.keep-ratio',
      needs: ['keep_ratio'],
      label: 'Keep proportions',
      text: { what: "Keep an element's proportions when it is resized, or let them change.", examples: ['lock the proportions', 'keep the aspect ratio', 'let me stretch it freely'] },
      uses: ['keep_ratio'],
      target: 'many',
      covers: ['keepAspectRatio'],
    },
    {
      id: 'arrange.inset',
      needs: ['inset'],
      label: 'Distance from the edge',
      text: { what: 'Set how far a placed element sits from the edge of the frame.', examples: ['20 pixels from the edge', 'move it further in from the corner'] },
      uses: ['inset', 'amount'],
      target: 'many',
      covers: ['inset'],
    },
    {
      id: 'arrange.replace-media',
      needs: ['asset'],
      label: 'Replace the file',
      text: {
        what: 'Replace the file a clip, picture or sound plays with another from the library, keeping where and when it is.',
        examples: ['replace this clip with the drone shot', 'swap the picture for the beach photo', 'use the other song instead'],
      },
      uses: ['asset'],
      target: 'one',
      covers: ['src'],
    },
  ],
};
