/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import { VALUE_DESCRIPTIONS } from '../../command-descriptions';
import { AMOUNT } from './shared';

import type { FamilyDef } from '../types';

export const STYLE: FamilyDef = {
  id: 'style',
  label: 'Style',
  exclusive: false,
  ask:
    'Does the command ask to change how something looks — its color or fill, a gradient, an outline, a shadow, how see-through it is, '
    + 'how it blends, rounded corners, a filter such as blur or black and white, the background color, how a picture fills its box — '
    + 'or a text: its font, size, bold, italic, how its lines line up, capitals, spacing, underline, or the words it says? '
    + 'For example "make it red", "bold", "blur the video", "change the title to Hello", "add a drop shadow", "round the corners". '
    + 'Not where it is or how big it is overall, and not an animation.',
  slots: {
    color: { kind: 'color', ask: 'Which color does the command ask for?' },
    gradient_kind: {
      kind: 'choice',
      ask: 'Which kind of gradient does the command ask for?',
      options: { linear: 'A straight gradient, from one side to the other.', radial: 'A round gradient, from the middle outward.' },
    },
    asset: { kind: 'asset', ask: 'Which picture or clip from the library should fill it?', types: ['image', 'video', 'sequence'] },
    outline_how: {
      kind: 'choice',
      ask: 'What does the command ask to do with the outline?',
      options: {
        add: 'Give it an outline, a border or a stroke.',
        thicker: 'Make the outline thicker.',
        thinner: 'Make the outline thinner.',
        recolor: 'Change only the color of the outline it has.',
        remove: 'Take the outline off.',
      },
    },
    stroke_width: { kind: 'number', text: 'How thick the outline is, in pixels.', units: ['px'] },
    shadow_how: {
      kind: 'choice',
      ask: 'What does the command ask to do with the shadow?',
      options: {
        add: 'Give it a drop shadow.',
        softer: 'Make the shadow softer, more blurred.',
        harder: 'Make the shadow harder, sharper.',
        remove: 'Take the shadow off.',
      },
    },
    effect_type: { kind: 'choice', ask: 'Which filter does the command describe?', options: { ...VALUE_DESCRIPTIONS.effectType! } },
    strength: { kind: 'number', text: "A filter's strength: pixels of blur, degrees of hue, or a percentage.", units: ['px', '%', 'deg'] },
    all_filters: { kind: 'onoff', ask: 'Does the command ask to take off every filter (yes), rather than one of them (no)?', yes: 'All', no: 'One' },
    opacity: { kind: 'number', text: 'How opaque it is, as a percentage: 100 is solid, 0 is invisible.', units: ['%'] },
    see_through: {
      kind: 'choice',
      ask: 'Does the command ask for it to be more see-through or less?',
      options: { more: 'More see-through, more transparent, fainter.', less: 'Less see-through, more solid, fully visible again.' },
    },
    blend: { kind: 'choice', ask: 'Which blend does the command ask for?', options: { ...VALUE_DESCRIPTIONS.blendMode! } },
    radius: { kind: 'number', text: 'How rounded the corners are, in pixels.', units: ['px'] },
    corners_how: {
      kind: 'choice',
      ask: 'What does the command ask of the corners?',
      options: { rounder: 'Rounder, more rounded, softer corners.', sharper: 'Sharper, square corners, not rounded.' },
    },
    which_corners: {
      kind: 'choice',
      ask: 'Which corners does the command mean?',
      options: {
        all: 'All the corners.',
        top: 'Only the top two corners.',
        bottom: 'Only the bottom two corners.',
        left: 'Only the left two corners.',
        right: 'Only the right two corners.',
        'top-left': 'Only the top left corner.',
        'top-right': 'Only the top right corner.',
        'bottom-left': 'Only the bottom left corner.',
        'bottom-right': 'Only the bottom right corner.',
      },
    },
    font: { kind: 'choice', ask: 'Which font does the command ask for?', options: {} },
    font_size: { kind: 'number', text: 'The size of its letters, in pixels.', units: ['px'] },
    size_dir: {
      kind: 'choice',
      ask: 'Does the command ask for the letters to be bigger or smaller?',
      options: { bigger: 'Bigger letters.', smaller: 'Smaller letters.' },
    },
    amount: AMOUNT,
    bold: { kind: 'onoff', ask: 'Does the command ask for bold (yes), rather than for not bold (no)?', yes: 'Bold', no: 'Not bold' },
    italic: { kind: 'onoff', ask: 'Does the command ask for italic (yes), rather than for upright letters (no)?', yes: 'Italic', no: 'Upright' },
    text_align: { kind: 'choice', ask: 'How does the command ask for the lines of the text to line up?', options: { ...VALUE_DESCRIPTIONS.textAlign! } },
    text_case: { kind: 'choice', ask: 'Which case does the command ask for?', options: { ...VALUE_DESCRIPTIONS.textCase! } },
    decoration: { kind: 'choice', ask: 'Which line does the command ask for on the text?', options: { ...VALUE_DESCRIPTIONS.textDecoration! } },
    spacing: { kind: 'number', text: 'The space between its letters, in pixels.', units: ['px'] },
    spacing_how: {
      kind: 'choice',
      ask: 'Does the command ask for the letters to be further apart or closer?',
      options: { wider: 'Further apart, more spaced out, wider.', tighter: 'Closer together, tighter.' },
    },
    leading: { kind: 'number', text: 'The space between its lines, as a percentage (100 is normal).', units: ['%', 'x'] },
    leading_how: {
      kind: 'choice',
      ask: 'Does the command ask for more space between the lines, or less?',
      options: { more: 'More space between the lines.', less: 'Less space between the lines, tighter.' },
    },
    baseline: {
      kind: 'choice',
      ask: 'Where does the command ask for the text to sit on its line?',
      options: { top: 'At the top.', middle: 'In the middle.', bottom: 'At the bottom.', alphabetic: 'On the baseline, as letters normally sit.' },
    },
    text_box: {
      kind: 'choice',
      ask: 'How does the command ask for the text box to size?',
      options: { auto: 'Grow and shrink with its words: sized to fit the text.', fixed: 'Keep a fixed box that the words wrap inside.' },
    },
    words: { kind: 'words', text: 'the new words a text says' },
    fit: { kind: 'choice', ask: 'How does the command ask for the picture or clip to fill its box?', options: { ...VALUE_DESCRIPTIONS.objectFit! } },
  },
  intents: [
    {
      id: 'style.color',
      needs: ['color'],
      label: 'Color',
      text: {
        what: "Change an element's color: the color of its text, or of its fill; a named color, lighter or darker, or the color of another element.",
        notFor: 'Not the background of the whole video, not a gradient, not an outline.',
        examples: ['make it red', 'turn the title blue', 'change the circle to light green', 'make it a bit darker', 'same color as the title'],
      },
      uses: ['color'],
      target: 'many',
      covers: ['color', 'fill', 'solidPaint.color'],
    },
    {
      id: 'style.gradient',
      needs: ['color'],
      label: 'Gradient',
      text: {
        what: 'Fill an element with a gradient from one color to another, straight or round.',
        examples: ['green to blue gradient', 'make the box a radial gradient', 'fade the fill from pink to orange'],
      },
      uses: ['color', 'gradient_kind'],
      target: 'many',
      covers: ['linearGradientPaint', 'radialGradientPaint', 'colorStop', 'replaceFill', 'offset'],
    },
    {
      id: 'style.fill-media',
      needs: ['asset'],
      label: 'Fill with a file',
      text: {
        what: 'Fill a shape with a picture or a clip from the library.',
        examples: ['fill the circle with the storm video', 'put the beach photo inside the square'],
      },
      uses: ['asset'],
      target: 'many',
      covers: ['imagePaint', 'videoPaint'],
    },
    {
      id: 'style.outline',
      needs: ['outline_how', 'stroke_width'],
      label: 'Outline',
      text: {
        what: 'Give an element an outline (a border, a stroke), change its color or thickness, or take it off.',
        examples: ['add a white outline', 'make the outline thicker', 'remove the border', 'give the text a black stroke'],
      },
      uses: ['outline_how', 'color', 'stroke_width', 'amount'],
      target: 'many',
      covers: ['stroke'],
    },
    {
      id: 'style.shadow',
      needs: ['shadow_how'],
      label: 'Shadow',
      text: {
        what: 'Give an element a drop shadow, make it softer or harder, or take it off.',
        examples: ['add a drop shadow', 'softer shadow', 'remove the shadow', 'give the title a shadow'],
      },
      uses: ['shadow_how', 'color'],
      target: 'many',
      covers: ['shadow', 'blur'],
    },
    {
      id: 'style.filter',
      needs: ['effect_type'],
      label: 'Filter',
      text: {
        what: 'Put a filter on an element, or change how strong it is: blur, black and white, sepia, inverted colors, a hue shift, darker, flatter or duller colors.',
        notFor: 'Not a blurred entrance or exit animation.',
        examples: ['blur the video', 'make it black and white', 'sepia tone', 'more blur', 'invert the colors'],
      },
      uses: ['effect_type', 'strength', 'amount'],
      target: 'many',
      covers: ['effect', 'type', 'value'],
    },
    {
      id: 'style.filter-remove',
      label: 'Remove a filter',
      text: {
        what: 'Take a filter off an element, or all of them.',
        examples: ['remove the blur', 'take all the filters off', 'no more black and white'],
      },
      uses: ['effect_type', 'all_filters'],
      target: 'many',
      covers: ['effect.remove'],
    },
    {
      id: 'style.opacity',
      needs: ['opacity', 'see_through'],
      label: 'Opacity',
      text: {
        what: 'Make an element more or less see-through, or set its opacity.',
        notFor: 'Not fading it in or out over time, not hiding it.',
        examples: ['set the opacity to 40%', 'make it more see-through', 'half transparent', 'make it solid again'],
      },
      uses: ['opacity', 'see_through', 'amount'],
      target: 'many',
      covers: ['opacity'],
    },
    {
      id: 'style.blend',
      needs: ['blend'],
      label: 'Blend',
      text: { what: 'Change how an element blends with what is under it: multiply, screen, overlay and the like.', examples: ['set it to multiply', 'blend mode screen', 'overlay blend'] },
      uses: ['blend'],
      target: 'many',
      covers: ['blendMode'],
    },
    {
      id: 'style.corners',
      needs: ['radius', 'corners_how'],
      label: 'Corners',
      text: {
        what: "Round an element's corners, all or some of them, or make them sharp.",
        examples: ['round the corners', 'make the corners 20 pixels', 'sharp corners', 'round only the top corners'],
      },
      uses: ['radius', 'corners_how', 'which_corners', 'amount'],
      target: 'many',
      covers: ['cornerRadius', 'cornerRadiusTopLeft', 'cornerRadiusTopRight', 'cornerRadiusBottomLeft', 'cornerRadiusBottomRight'],
    },
    {
      id: 'style.background',
      needs: ['color'],
      label: 'Background',
      text: {
        what: 'Change the background color of the scene, or of the canvas around the scenes.',
        notFor: 'Not the color of one element.',
        examples: ['make the background black', 'change the scene background to navy', 'make the canvas grey'],
      },
      uses: ['color'],
      target: 'none',
      covers: ['scene.fill', 'background', 'stage'],
    },
    {
      id: 'style.font',
      needs: ['font'],
      label: 'Font',
      text: { what: 'Change the font, the typeface, of a text.', examples: ['use Montserrat', 'change the font to Inter', 'a different typeface'] },
      uses: ['font'],
      target: 'many',
      tags: ['text', 'captions'],
      covers: ['fontFamily'],
    },
    {
      id: 'style.text-size',
      needs: ['font_size', 'size_dir'],
      label: 'Text size',
      text: {
        what: 'Change the size of the letters of a text: a size in pixels, bigger or smaller.',
        examples: ['font size 48', 'bigger letters', 'make the text smaller'],
      },
      uses: ['font_size', 'size_dir', 'amount'],
      target: 'many',
      tags: ['text'],
      covers: ['fontSize'],
    },
    {
      id: 'style.bold',
      label: 'Bold',
      text: { what: 'Make a text bold, or not bold.', examples: ['make it bold', 'not bold anymore', 'bold the heading'] },
      uses: ['bold'],
      target: 'many',
      tags: ['text'],
      covers: ['fontWeight'],
    },
    {
      id: 'style.italic',
      label: 'Italic',
      text: { what: 'Make a text italic, or upright again.', examples: ['italic', 'make the subtitle slanted', 'no italics'] },
      uses: ['italic'],
      target: 'many',
      tags: ['text'],
      covers: ['fontStyle'],
    },
    {
      id: 'style.text-align',
      needs: ['text_align'],
      label: 'Text alignment',
      text: {
        what: 'How the lines of a text line up inside its box: left, centered or right.',
        notFor: 'Not lining several elements up with each other, and not a place in the frame.',
        examples: ['align the text left', 'center the lines of the caption', 'right-align the words'],
      },
      uses: ['text_align'],
      target: 'many',
      tags: ['text'],
      covers: ['textAlign'],
    },
    {
      id: 'style.text-case',
      needs: ['text_case'],
      label: 'Capitals',
      text: { what: 'Show a text in capitals, in lowercase, or as written.', examples: ['all caps', 'make it lowercase', 'normal case'] },
      uses: ['text_case'],
      target: 'many',
      tags: ['text'],
      covers: ['textCase'],
    },
    {
      id: 'style.decoration',
      needs: ['decoration'],
      label: 'Underline',
      text: { what: 'Underline a text or strike it through, or take the line off.', examples: ['underline it', 'strike through the price', 'no underline'] },
      uses: ['decoration'],
      target: 'many',
      tags: ['text'],
      covers: ['textDecoration'],
    },
    {
      id: 'style.letter-spacing',
      needs: ['spacing', 'spacing_how'],
      label: 'Letter spacing',
      text: { what: 'Change the space between the letters of a text.', examples: ['space the letters out', 'tighter letter spacing', 'letter spacing 4'] },
      uses: ['spacing', 'spacing_how', 'amount'],
      target: 'many',
      tags: ['text'],
      covers: ['letterSpacing'],
    },
    {
      id: 'style.line-spacing',
      needs: ['leading', 'leading_how'],
      label: 'Line spacing',
      text: { what: 'Change the space between the lines of a text.', examples: ['more space between the lines', 'tighter line height', 'line spacing 120 percent'] },
      uses: ['leading', 'leading_how', 'amount'],
      target: 'many',
      tags: ['text'],
      covers: ['leading'],
    },
    {
      id: 'style.baseline',
      needs: ['baseline'],
      label: 'Baseline',
      text: { what: 'Where a text sits on its line: top, middle, bottom or the baseline.', examples: ['set the text baseline to middle', 'baseline alphabetic'] },
      uses: ['baseline'],
      target: 'many',
      tags: ['text'],
      covers: ['textBaseline'],
    },
    {
      id: 'style.text-box',
      needs: ['text_box'],
      label: 'Text box',
      text: { what: 'Let a text box grow with its words, or keep it a fixed size the words wrap in.', examples: ['make the text box fit the words', 'fixed size text box', 'auto size the text'] },
      uses: ['text_box'],
      target: 'many',
      tags: ['text'],
      covers: ['text.width', 'text.height'],
    },
    {
      id: 'style.words',
      needs: ['words'],
      label: 'New words',
      text: {
        what: 'Replace the words a text says with new words the command gives.',
        notFor: 'Not renaming its layer, not adding a new text, and not writing new words the command does not give.',
        examples: ['change the title to Summer Sale', 'make the subtitle say see you tomorrow', 'the text should read follow for more'],
      },
      uses: ['words'],
      target: 'one',
      tags: ['text'],
      covers: ['editText'],
    },
    {
      id: 'style.word',
      needs: ['words'],
      label: 'Style a word',
      text: {
        what: 'Style only one word, or a few words, inside a text — their color, bold, italic, size, underline, capitals — not the whole text.',
        examples: ['make the word STORM green', 'bold the word tonight', 'make "sale" red and bigger'],
      },
      uses: ['words'],
      target: 'one',
      tags: ['text'],
      covers: ['textRange'],
    },
    {
      id: 'style.fit',
      needs: ['fit'],
      label: 'Fit',
      text: {
        what: 'How a picture or clip fills its box: cropped to fill it, fitted whole inside it, or stretched to it.',
        examples: ['crop the picture to fill its box', 'show the whole photo without cropping', 'stretch the video to fit'],
      },
      uses: ['fit'],
      target: 'many',
      tags: ['video', 'image', 'rect', 'ellipse', 'polygon'],
      covers: ['objectFit'],
    },
  ],
};
