/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * What every option the voice bar puts to Jev means, in one plain sentence.
 *
 * Jev picks an option by what its description says, not by its name, so these
 * sentences decide how well a command in the person's own words is understood:
 * "snappy" has to say what snappy feels like, and "slideRight" which way it
 * goes. The vocabulary documents each prop but not each value of one, so the
 * values are described here — and a test fails when the vocabulary gains a
 * value this file does not describe, so the two cannot drift apart.
 */

/** The editor's own commands, by id: what each one does, not what it is called. */
export const COMMAND_DESCRIPTIONS: Record<string, string> = {
  "edit.undo": "Take back the last change.",
  "edit.again": "Do the last command once more.",
  "edit.redo": "Put back the change that was just undone.",
  "edit.delete": "Delete the selected elements from the video.",
  "edit.ripple-delete": "Delete the selected clips and close the gap they leave, pulling everything after them earlier.",
  "edit.duplicate": "Make a copy of the selected elements, in the same place.",
  "edit.group": "Put the selected elements together in a group, so they move as one.",
  "edit.ungroup": "Break a group apart into its elements.",
  "edit.wrap-scene": "Turn the selected elements into a scene of their own.",
  "edit.wrap-sequence": "Put the selected clips in a sequence, so they play one after another.",
  "edit.unwrap-sequence": "Take the clips back out of a sequence.",
  "edit.split": "Cut the clips under the playhead in two, at the playhead.",
  "edit.copy": "Copy the selected elements to the clipboard.",
  "edit.paste": "Paste what was copied.",
  "edit.cut": "Cut the selected elements to the clipboard, removing them.",
  "edit.hide": "Hide the selected elements, or show them again if they are hidden — the same as setting whether they are shown.",
  "edit.select-all": "Select every element.",
  "edit.select-parents": "Select the group or scene the selection sits in.",
  "edit.select-children": "Select the elements inside the selected group.",
  "edit.deselect": "Select nothing.",
  "edit.bring-front": "Move the selected element in front of everything else in the layer order, drawn on top — not a place in the frame.",
  "edit.send-back": "Move the selected element behind everything else in the layer order, drawn underneath — not a place in the frame such as the bottom.",
  "edit.snapping": "Turn snapping on or off while dragging.",
  "edit.nudge-earlier": "Move the selected clips one frame earlier in time.",
  "edit.nudge-later": "Move the selected clips one frame later in time.",
  "edit.nudge-earlier-far": "Move the selected clips ten frames earlier in time.",
  "edit.nudge-later-far": "Move the selected clips ten frames later in time.",
  "canvas.zoom-in": "Zoom the canvas view in, closer.",
  "canvas.zoom-out": "Zoom the canvas view out, further away.",
  "canvas.actual-size": "Show the canvas at its actual size, 100 percent.",
  "canvas.zoom-fit": "Zoom the canvas view so the whole frame fits the screen.",
  "canvas.zoom-selection": "Zoom the canvas view in on the selected element.",
  "canvas.move-tool": "Switch to the move tool, for selecting and dragging.",
  "canvas.hand-tool": "Switch to the hand tool, for panning the view.",
  "canvas.frame-tool": "Switch to the frame tool, for drawing a new frame or scene.",
  "canvas.text-tool": "Switch to the text tool, for adding a new text element.",
  "canvas.component-tool": "Switch to the shape tool, for drawing a new shape.",
  "canvas.nudge-left": "Move the selected element one pixel to the left.",
  "canvas.nudge-right": "Move the selected element one pixel to the right.",
  "canvas.nudge-up": "Move the selected element one pixel up.",
  "canvas.nudge-down": "Move the selected element one pixel down.",
  "canvas.nudge-left-far": "Move the selected element ten pixels to the left.",
  "canvas.nudge-right-far": "Move the selected element ten pixels to the right.",
  "canvas.nudge-up-far": "Move the selected element ten pixels up.",
  "canvas.nudge-down-far": "Move the selected element ten pixels down.",
  "transport.play": "Play the video, or pause it if it is playing.",
  "transport.frame-back": "Step the playhead back one frame.",
  "transport.frame-forward": "Step the playhead forward one frame.",
  "transport.second-back": "Jump the playhead back one second.",
  "transport.second-forward": "Jump the playhead forward one second.",
  "transport.start": "Go to the start of the video.",
  "transport.end": "Go to the end of the video.",
  "transport.previous-cut": "Jump the playhead to the previous cut between clips.",
  "transport.next-cut": "Jump the playhead to the next cut between clips.",
  "transport.shuttle-back": "Play the video backwards.",
  "transport.shuttle-forward": "Play the video fast forward.",
  "transport.pause-shuttle": "Stop playing backwards or fast forward.",
  "range.in": "Mark where the part of the video to export begins, at the playhead.",
  "range.out": "Mark where the part of the video to export ends, at the playhead.",
  "range.clear": "Clear the marked part to export, so the whole video exports.",
  "range.marker": "Put a marker on the timeline at the playhead.",
  "timeline.zoom-in": "Zoom the timeline in, to see less time in more detail.",
  "timeline.zoom-out": "Zoom the timeline out, to see more time.",
  "timeline.fit": "Zoom the timeline so the whole video fits.",
  "timeline.zoom-selection": "Zoom the timeline to the selected clips.",
  "workspace.storyboard": "Switch to the storyboard workspace, all the scenes side by side.",
  "workspace.edit": "Switch to the edit workspace.",
  "workspace.motion": "Switch to the motion workspace, for animation.",
  "panel.assets": "Show or hide the assets panel of media files.",
  "panel.inspector": "Show or hide the inspector panel of settings.",
  "panel.timeline": "Expand or collapse the timeline.",
  "panel.history": "Open the version history of the project.",
  "view.theme": "Switch the editor's look between Noir and Glass.",
  "view.hide-interface": "Hide the editor's panels to see only the video.",
  "export.video": "Export the video to a file.",
  "export.library": "Open the library of past exports.",
  "export.settings": "Open the export settings.",
  "ai.generate": "Open AI Generate, to make an image, a video or a voice.",
  "agent.open": "Open this project in the person's coding agent.",
};

/** What the bar can do beyond the named commands, as options of the same question. */
export const ACTION_DESCRIPTIONS: Record<string, string> = {
  "edit-properties": "Change how an element looks, where it is or when it plays: its place in the frame, position, size, color, font, opacity, rotation, timing or any other setting — one change or several.",
  "change-text": "Replace the words a text element says with new words the command gives.",
  "add-animation": "Give an element an entrance or an exit: fading, sliding, growing, spinning, blurring in, or appearing word by word.",
  "add-effect": "Put a filter on an element: blur, black and white, sepia, inverted colors, a hue shift, darker, flatter or duller colors.",
  "remove-animation": "Take an entrance or exit animation off an element.",
  "needs-writing": "Write or rewrite words creatively — a new headline, a punchier line, a script — which needs a writer rather than a setting.",
  "none": "Not something the video editor can do, or not a command at all.",
};

/** The props a command may ask to change, finishing "Does the command ask to change …?" */
export const PROP_DESCRIPTIONS: Record<string, string> = {
  place: "where the element should sit in the frame, named as a spot — the center, a corner, an edge, or the upper or lower third (not a distance to move it, and not the side an animation comes in from)",
  x: "its horizontal position — moving it left or right",
  y: "its vertical position — moving it up or down",
  width: "how wide it is",
  height: "how tall it is",
  rotation: "how far it is turned or tilted",
  scale: "how big it is overall — making it bigger or smaller (not louder, faster or longer)",
  opacity: "how see-through it is — its opacity or transparency",
  color: "its color — the color of its text, or of its fill",
  cornerRadius: "how rounded its corners are",
  blendMode: "how it blends with what is under it — multiply, screen, overlay and the like",
  hidden: "whether it is shown at all or hidden — switched off or on, not faded in or out",
  fontSize: "the size of its text",
  fontFamily: "its font, the typeface of its text",
  fontWeight: "whether its text is bold",
  fontStyle: "whether its text is italic",
  letterSpacing: "the space between its letters",
  leading: "the space between its lines of text",
  textAlign: "how its text lines up — left, centered or right",
  textCase: "whether its text shows in capitals or in lowercase",
  textDecoration: "whether its text is underlined or struck through",
  objectFit: "how a picture or clip fills its box — cropped to fill, fitted whole, or stretched",
  volume: "how loud its sound is",
  muted: "whether its sound is on or off",
  playbackRate: "how fast it plays — its speed",
  start: "when it starts in time",
  end: "when it ends in time",
  name: "its name in the layers list",
  preset: "the style of the captions, switched to another named caption style — only when the command is about captions",
  verticalAlign: "whether the captions sit at the top, middle or bottom",
};

/** The values of each enum the bar asks about. */
export const VALUE_DESCRIPTIONS: Record<string, Record<string, string>> = {
  place: {
    "top-left": "In the top left corner of the frame.",
    top: "At the top of the frame, centered left to right.",
    "top-right": "In the top right corner of the frame.",
    left: "At the left edge of the frame, halfway down.",
    center: "In the middle of the frame, centered both ways.",
    right: "At the right edge of the frame, halfway down.",
    "bottom-left": "In the bottom left corner of the frame.",
    bottom: "At the bottom of the frame, centered left to right.",
    "bottom-right": "In the bottom right corner of the frame.",
    "upper-third": "Centered on the line a third of the way down the frame — the upper third.",
    "lower-third": "Centered on the line two thirds of the way down the frame — the lower third, where names and titles usually go.",
  },
  blendMode: {
    sourceOver: "Normal: drawn over what is under it, no blending.",
    multiply: "Multiply: darkens what is under it, like ink on paper; white disappears.",
    screen: "Screen: lightens what is under it, like light on light; black disappears.",
    overlay: "Overlay: more contrast — darks get darker and lights lighter.",
    darken: "Darken: keeps whichever is darker, it or what is under it.",
    lighten: "Lighten: keeps whichever is lighter, it or what is under it.",
    colorDodge: "Color dodge: brightens what is under it strongly, a glowing burn-out.",
    colorBurn: "Color burn: darkens what is under it strongly, deep and saturated.",
    hardLight: "Hard light: strong contrast, like a harsh spotlight.",
    softLight: "Soft light: gentle contrast, like a diffused spotlight.",
    difference: "Difference: subtracts colors, inverting where it overlaps bright areas.",
    exclusion: "Exclusion: like difference but softer and grayer.",
    hue: "Hue: takes its hue, keeping the brightness of what is under it.",
    saturation: "Saturation: takes its saturation, keeping the rest of what is under it.",
    color: "Color: takes its hue and saturation, keeping the brightness of what is under it — tints it.",
    luminosity: "Luminosity: takes its brightness, keeping the colors of what is under it.",
  },
  fontWeight: {
    normal: "Regular weight, not bold.",
    bold: "Bold, heavy letters.",
  },
  fontStyle: {
    normal: "Upright letters, not italic.",
    italic: "Italic, slanted letters.",
    oblique: "Oblique: the upright letters slanted.",
  },
  textAlign: {
    left: "Lined up on the left.",
    center: "Centered.",
    right: "Lined up on the right.",
  },
  textCase: {
    original: "As written, capitals where the words have them.",
    upper: "All capitals, uppercase.",
    lower: "All lowercase.",
  },
  textDecoration: {
    none: "No line: not underlined or struck through.",
    underline: "Underlined.",
    lineThrough: "Struck through with a line.",
    "underline lineThrough": "Both underlined and struck through.",
  },
  objectFit: {
    cover: "Fills the whole box, cropping what does not fit.",
    contain: "Shows the whole picture inside the box, with empty space around it if the shapes differ.",
    fill: "Stretched to fill the box exactly, even if that distorts it.",
  },
  preset: {
    classic: "Classic: one clean centered line in a rounded sans, lowercase — a plain subtitle.",
    cascade: "Cascade: light left-aligned lines stacking down the frame like a transcript.",
    spotlight: "Spotlight: bold centered words with the word being said lit up in cyan.",
    whisper: "Whisper: small, light and understated, with airy line spacing.",
    paper: "Paper: thin, tightly set lines, like print on a page.",
    guinea: "Guinea: bold display letters in capitals, centered and punchy.",
    stark: "Stark: heavy capitals, high contrast, one line at a time.",
    pop: "Pop: one big word at a time in heavy capitals, landing with a snap in green — the TikTok look.",
    karaoke: "Karaoke: the line sits still and fills with color behind the voice, like a lyric video.",
    typewriter: "Typewriter: typewriter letters, the line arriving a word at a time and staying.",
    banner: "Banner: short wide lines in capitals low in the frame, like a news ticker.",
    punch: "Punch: the said word swells out of the line in loud comic capitals with a red accent.",
    marquee: "Marquee: two or three big comic words at a time, rolling fast.",
  },
  verticalAlign: {
    top: "Captions at the top of the frame.",
    center: "Captions in the middle of the frame.",
    bottom: "Captions at the bottom of the frame.",
  },
  animationType: {
    fade: "Fade: fades in from invisible, or fades out to invisible.",
    gain: "Gain: the sound fades up as it starts, or down as it ends — for audio, nothing visible.",
    grow: "Grow: starts smaller and grows to its size as it comes in; shrinks as it leaves.",
    shrink: "Shrink: starts bigger and shrinks to its size as it comes in; grows as it leaves.",
    blur: "Blur: comes into focus from a blur, or blurs away.",
    slideLeft: "Slide left: moves to the left — comes in from the right, or leaves off to the left.",
    slideRight: "Slide right: moves to the right — comes in from the left, or leaves off to the right.",
    slideUp: "Slide up: moves upward — comes in from below, or leaves off the top.",
    slideDown: "Slide down: moves downward — comes in from above, or leaves off the bottom.",
    spin: "Spin: spins in while growing from nothing, or spins away to nothing.",
    twist: "Twist: turns and drifts into place from larger, or twists away.",
    appearWord: "Appear word by word: the text reveals one word at a time.",
    appearChar: "Appear letter by letter: the text types on one letter at a time.",
    scramble: "Scramble: the letters shuffle randomly until they settle into the text.",
  },
  animationPhase: {
    in: "An entrance: how it comes in when it starts.",
    out: "An exit: how it leaves when it ends.",
  },
  easing: {
    linear: "Linear: the same speed all the way, mechanical.",
    easeIn: "Ease in: starts slow and speeds up.",
    easeOut: "Ease out: starts fast and slows to a stop — smooth.",
    easeInOut: "Ease in and out: slow at both ends, faster in the middle.",
    gentle: "Gentle: a soft spring that settles slowly with a slight sway.",
    snappy: "Snappy: quick and crisp, stopping fast with barely any bounce.",
    bouncy: "Bouncy: springs past its mark and bounces back before settling.",
    strong: "Strong: a hard spring with a big overshoot and a firm snap back.",
  },
  effectType: {
    blur: "Blur: makes it soft and out of focus.",
    brightness: "Brightness: makes it darker, dimmer.",
    contrast: "Contrast: makes it flatter and washed out, less contrast.",
    grayscale: "Grayscale: black and white, no color.",
    hueRotate: "Hue shift: turns all its colors around the color wheel.",
    invert: "Invert: flips its colors, like a photo negative.",
    saturate: "Saturation: mutes its colors toward gray, duller.",
    sepia: "Sepia: a warm brown old-photo tone.",
  },
};

/** Which vocabulary enum each described set is, for the test that keeps them in step. */
export const DESCRIBED_ENUMS: ReadonlyArray<{ key: string; tag: string; prop: string }> = [
  { key: "place", tag: "text", prop: "place" },
  { key: "blendMode", tag: "rect", prop: "blendMode" },
  { key: "fontWeight", tag: "text", prop: "fontWeight" },
  { key: "fontStyle", tag: "text", prop: "fontStyle" },
  { key: "textAlign", tag: "text", prop: "textAlign" },
  { key: "textCase", tag: "text", prop: "textCase" },
  { key: "textDecoration", tag: "text", prop: "textDecoration" },
  { key: "objectFit", tag: "video", prop: "objectFit" },
  { key: "preset", tag: "captions", prop: "preset" },
  { key: "verticalAlign", tag: "captions", prop: "verticalAlign" },
  { key: "animationType", tag: "animation", prop: "type" },
  { key: "animationPhase", tag: "animation", prop: "phase" },
  { key: "easing", tag: "animation", prop: "easing" },
  { key: "effectType", tag: "effect", prop: "type" },
];

/** Colors a command can name, and what each one is set to. */
export const COLOR_NAMES: Record<string, { hex: string; description: string }> = {
  red: { hex: "#ff3b30", description: "Red." },
  orange: { hex: "#ff9500", description: "Orange." },
  yellow: { hex: "#ffcc00", description: "Yellow, gold." },
  green: { hex: "#34c759", description: "Green." },
  teal: { hex: "#30b0c7", description: "Teal, turquoise." },
  blue: { hex: "#0a84ff", description: "Blue." },
  navy: { hex: "#1c2a6b", description: "Navy, dark blue." },
  purple: { hex: "#af52de", description: "Purple, violet." },
  pink: { hex: "#ff2d55", description: "Pink, magenta." },
  brown: { hex: "#a2845e", description: "Brown." },
  white: { hex: "#ffffff", description: "White." },
  black: { hex: "#000000", description: "Black." },
  gray: { hex: "#8e8e93", description: "Gray, grey, silver." },
};

/** The relative words, as the options of their questions. */
export const DIRECTION_DESCRIPTIONS: Record<string, string> = {
  left: "Toward the left.",
  right: "Toward the right.",
  up: "Upward, higher.",
  down: "Downward, lower.",
  none: "No direction is given.",
};

export const SIZE_DESCRIPTIONS: Record<string, string> = {
  bigger: "Bigger, larger, enlarged.",
  smaller: "Smaller, reduced.",
  none: "The command does not ask for it to be bigger or smaller.",
};

/** The levels of how much, least first. */
export const AMOUNT_LEVELS = ["a little", "noticeably", "a lot"] as const;
